services:
  - type: web
    name: lottery-website
    env: php
    plan: free
    region: singapore
    buildCommand: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && npm install && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: Lottery
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: lottery-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: lottery-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: lottery-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: lottery-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: lottery-db
          property: password

databases:
  - name: lottery-db
    plan: free
    region: singapore
